---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: scaledjobs.keda.sh
spec:
  group: keda.sh
  names:
    kind: ScaledJob
    listKind: ScaledJobList
    plural: scaledjobs
    shortNames:
      - sj
    singular: scaledjob
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      additionalPrinterColumns:
        - jsonPath: .spec.minReplicaCount
          name: Min
          type: integer
        - jsonPath: .spec.maxReplicaCount
          name: Max
          type: integer
        - jsonPath: .status.conditions[?(@.type=="Ready")].status
          name: Ready
          type: string
        - jsonPath: .status.conditions[?(@.type=="Active")].status
          name: Active
          type: string
        - jsonPath: .status.conditions[?(@.type=="Paused")].status
          name: Paused
          type: string
        - jsonPath: .status.triggersTypes
          name: Triggers
          type: string
        - jsonPath: .status.authenticationsTypes
          name: Authentications
          type: string
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
